# Generated by Django 4.2.3 on 2023-12-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_watchlist_avg_ratings_watchlist_number_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='avg_ratings',
            new_name='avg_rating',
        ),
    ]
